In [2]:
import numpy as np
import scipy.linalg as la
import pandas as pd

In [49]:
#Produção total
V = pd.read_excel('./dados/Matriz_de_Insumo_Produto_2015_Nivel_67.xls',sheet_name='01',skiprows=5,skipfooter=5,usecols=[*range(7,74)],header=None)


In [51]:
V.head()

7     8   9   10  11  12  13  14  15  16  ...  64  65   66  67  68  69  \
0   10551   321   8   0   0   0   0   0   0   0  ...   0   0  156   0   0   0   
1   28173  1641  51   0   0   0   0   0   0   0  ...   0   0  110   0   0   0   
2    8931    11   0   0   0   0   0   0   0   0  ...   0   0    1   0   0   0   
3   45840   239   1   0   0   0   0   0   0   0  ...   0   0    0   0   0   0   
4  106355  2773  42   0   0   0   0   0   0   0  ...   0   0    0   0   0   0   

   70  71  72  73  
0   0   0   0   0  
1   0   0   0   0  
2   0   0   0   0  
3   0   0   0   0  
4   0   0   0   0  

[5 rows x 67 columns]

In [54]:

V = np.transpose(V)
#Impostos
Imp = pd.read_excel('./dados/Matriz_de_Insumo_Produto_2015_Nivel_67.xls',sheet_name='01',skiprows=5,skipfooter=5,usecols=[5],header=None)
#Consumo intermediário produção nacional
Un = pd.read_excel('./dados/Matriz_de_Insumo_Produto_2015_Nivel_67.xls',sheet_name='03',skiprows=5,skipfooter=4,usecols=[*range(3,70)],header=None)
#Demanda Final Nacional
Fn = pd.read_excel('./dados/Matriz_de_Insumo_Produto_2015_Nivel_67.xls',sheet_name='03',skiprows=5,skipfooter=4,usecols=[*range(71,77)],header=None)

#Consumo intermediário produção importados
Um = pd.read_excel('./dados/Matriz_de_Insumo_Produto_2015_Nivel_67.xls',sheet_name='04',skiprows=5,skipfooter=4,usecols=[*range(3,70)],header=None)
#Demanda Final Nacional importados
Fm = pd.read_excel('./dados/Matriz_de_Insumo_Produto_2015_Nivel_67.xls',sheet_name='04',skiprows=5,skipfooter=4,usecols=[*range(71,77)],header=None)


In [63]:
Fn.shape

(127, 6)

In [22]:
g = np.matmul(V,np.ones(127)) ## Produção total por atividade

In [27]:
q = np.transpose(np.matmul(np.transpose(np.ones(67)),V)) ## Produção total por produto

In [31]:
D = np.matmul(V,np.linalg.inv(np.diag(q))) # market share

In [57]:
D.shape

(67, 127)

In [58]:
Un.shape

(127, 67)

In [79]:
Bn = np.matmul(Un,np.linalg.inv(np.diag(g))) # consumo intermediário nacional
A = np.matmul(D,Bn) # coeficientes técnicos intersetoriais nacionais

In [77]:
fn = np.matmul(Fn,np.transpose(np.ones(6))) # soma da demanda final

In [75]:

e = np.matmul(D,fn) #Demanda final ( nacional )

In [81]:
Bm = np.matmul(Um,np.linalg.inv(np.diag(g))) # consumo intermediário importado


In [82]:
A_plus = np.matmul(D,Bn+Bm) # coeficientes técnicos ampliada ( contém insumos nacionais e importados )

In [85]:
A_plus.shape

(67, 67)

In [67]:
e.shape

(67, 6)

In [87]:
A.shape

(67, 67)

In [94]:
L = np.linalg.inv(np.eye(A.shape[0])-A) # leontief

In [95]:
L

array([[1.02773202e+00, 5.44363300e-02, 1.36446721e-02, ...,
        2.08792617e-03, 8.24716207e-03, 0.00000000e+00],
       [3.11757093e-03, 1.04062171e+00, 5.55800662e-03, ...,
        5.35815772e-04, 3.48428117e-03, 0.00000000e+00],
       [3.57783232e-03, 9.13127880e-03, 1.05121253e+00, ...,
        4.36741287e-04, 7.87761572e-04, 0.00000000e+00],
       ...,
       [2.87744016e-04, 5.26111772e-04, 2.95272245e-04, ...,
        1.02516733e+00, 1.00216176e-02, 0.00000000e+00],
       [1.49719447e-03, 1.52110501e-03, 1.18862912e-03, ...,
        1.90224048e-03, 1.00408244e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [6]:
Q = np.array([[280,120],[12,8]])
q = np.array([575,20])

print(Q)
print(q)

[[280 120]
 [ 12   8]]
[575  20]


In [14]:
A= np.matmul(Q,np.linalg.inv(np.diag(q)))

In [19]:
eigvector,eigvalues = la.eig(np.matrix.transpose(A))

In [38]:
lambdas = max(eigvector).real
pos_vec = np.argmax(eigvector)

In [39]:
max_eigvectors = eigvalues[:,pos_vec].reshape(2,1)

In [40]:
r = (1-lambdas)/lambdas

In [37]:
lambdas.real

0.8

In [45]:
max_eigvectors/max_eigvectors[0]

array([[ 1.],
       [15.]])

## Importação de dados reais

In [1]:
import pandas as pd


Undefined variable: import
